	mysystem u0 (
		.done_bit_export                    (<connected-to-done_bit_export>),                    //               done_bit.export
		.memory_mem_a                       (<connected-to-memory_mem_a>),                       //                 memory.mem_a
		.memory_mem_ba                      (<connected-to-memory_mem_ba>),                      //                       .mem_ba
		.memory_mem_ck                      (<connected-to-memory_mem_ck>),                      //                       .mem_ck
		.memory_mem_ck_n                    (<connected-to-memory_mem_ck_n>),                    //                       .mem_ck_n
		.memory_mem_cke                     (<connected-to-memory_mem_cke>),                     //                       .mem_cke
		.memory_mem_cs_n                    (<connected-to-memory_mem_cs_n>),                    //                       .mem_cs_n
		.memory_mem_ras_n                   (<connected-to-memory_mem_ras_n>),                   //                       .mem_ras_n
		.memory_mem_cas_n                   (<connected-to-memory_mem_cas_n>),                   //                       .mem_cas_n
		.memory_mem_we_n                    (<connected-to-memory_mem_we_n>),                    //                       .mem_we_n
		.memory_mem_reset_n                 (<connected-to-memory_mem_reset_n>),                 //                       .mem_reset_n
		.memory_mem_dq                      (<connected-to-memory_mem_dq>),                      //                       .mem_dq
		.memory_mem_dqs                     (<connected-to-memory_mem_dqs>),                     //                       .mem_dqs
		.memory_mem_dqs_n                   (<connected-to-memory_mem_dqs_n>),                   //                       .mem_dqs_n
		.memory_mem_odt                     (<connected-to-memory_mem_odt>),                     //                       .mem_odt
		.memory_mem_dm                      (<connected-to-memory_mem_dm>),                      //                       .mem_dm
		.memory_oct_rzqin                   (<connected-to-memory_oct_rzqin>),                   //                       .oct_rzqin
		.ready_bit_export                   (<connected-to-ready_bit_export>),                   //              ready_bit.export
		.sdram_clk_clk                      (<connected-to-sdram_clk_clk>),                      //              sdram_clk.clk
		.sdram_wire_addr                    (<connected-to-sdram_wire_addr>),                    //             sdram_wire.addr
		.sdram_wire_ba                      (<connected-to-sdram_wire_ba>),                      //                       .ba
		.sdram_wire_cas_n                   (<connected-to-sdram_wire_cas_n>),                   //                       .cas_n
		.sdram_wire_cke                     (<connected-to-sdram_wire_cke>),                     //                       .cke
		.sdram_wire_cs_n                    (<connected-to-sdram_wire_cs_n>),                    //                       .cs_n
		.sdram_wire_dq                      (<connected-to-sdram_wire_dq>),                      //                       .dq
		.sdram_wire_dqm                     (<connected-to-sdram_wire_dqm>),                     //                       .dqm
		.sdram_wire_ras_n                   (<connected-to-sdram_wire_ras_n>),                   //                       .ras_n
		.sdram_wire_we_n                    (<connected-to-sdram_wire_we_n>),                    //                       .we_n
		.system_ref_clk_clk                 (<connected-to-system_ref_clk_clk>),                 //         system_ref_clk.clk
		.system_ref_reset_reset             (<connected-to-system_ref_reset_reset>),             //       system_ref_reset.reset
		.sdram_master_0_control_done_out    (<connected-to-sdram_master_0_control_done_out>),    // sdram_master_0_control.done_out
		.sdram_master_0_control_ready_in    (<connected-to-sdram_master_0_control_ready_in>),    //                       .ready_in
		.sdram_master_0_debug_max_out       (<connected-to-sdram_master_0_debug_max_out>),       //   sdram_master_0_debug.max_out
		.sdram_master_0_debug_min_out       (<connected-to-sdram_master_0_debug_min_out>),       //                       .min_out
		.sdram_master_0_debug_state_out     (<connected-to-sdram_master_0_debug_state_out>),     //                       .state_out
		.sdram_master_0_debug_test_rd_wr_in (<connected-to-sdram_master_0_debug_test_rd_wr_in>), //                       .test_rd_wr_in
		.sdram_master_0_debug_read_index_in (<connected-to-sdram_master_0_debug_read_index_in>)  //                       .read_index_in
	);

